### ISSUE TITLE
Arduino EEPROM does not exist?

### ISSUE THREAD

**Issue by JamesG9802** [JamesG9802/open_source_insulin_pump#10]
Unfortunately, the version of Arduino we have (Arduino Nano 33 IoT) does not have an EEPROM chip for persistent data storage. This means that all data on the arduino will be wiped unless we use the flash memory on the arduino (not recommended) for storage. The flash memory has a limited number of writes and is used to store the bootloaded for the arduino.

**Suggestion:**
We utilize the Arduino's bluetooth capability to connect with another device (phone?) to store data. This also solves another problem of how to get user data onto the Arduino without preprogramming it everytime.

**Comment by mishlosh** [comment]
For now we'll hard code a profile, and assume the arduino will be permanently on with it's own battery. The bluetooth will be used for simulating input data from a CGM and simulating output instructions to pump
